### ISSUE TITLE
Ionic Upload Blank screen

### ISSUE THREAD

**Issue by Anton-Interon** [leob/ionic-quickstarter#24]
Hi 

I'm having a problem where ionic upload produces a blank screen.

Having said that, ionic serve --lab works fine.

Thanks

**Comment by Anton-Interon** [comment]
After further investigation I see there is an error : 
Error: ENOENT, no such file or directory 'C:\Users****_\Documents\Visual Studio 2015\Projects\**__\_***\www.zip'

**Comment by leob** [comment]
Hey you are right and this is a know issue when you use "ionic upload" and the Ionic View app, but I've already documented a workaround here in the README:

https://github.com/leob/ionic-quickstarter#a-note-about-ionic-upload-and-the-ionic-view-app

Please read it and it will all become clear.

By the way, personally I totally advise AGAINST using Ionic View. Do yourself a big favor and just build and install an APK (Android), and don't bother using Ionic View. I've had nothing but problems and negative experiences with it.

Many times I've seen that apps run way more slow and unreliable when using Ionic View compared to just building and installing an Android APK (assuming that you target Android), which takes just 2 minutes and is almost as fast and easy as Ionic View and gives you a speedy app which can use ALL of the device's hardware functions.

The only case where Ionic View might give you an advantage is when you need to target iOS because I believe the process to build and install an iOS IPA is much more of a hassle compared to an Android APK.

Closing the issue now.
