### ISSUE TITLE
camera not working

### ISSUE THREAD

**Issue by keiseele** [leob/ionic-quickstarter#37]
when I run ionic run android and run the app in my devise, the button for take a picture or get from file is not working. I added the permission to the android manifest and still not working.

**Comment by leob** [comment]
In what sense is it not working?

I suppose that, when you tap the "Profile picture" placeholder in the "User Profile" page, you do get a popup menu at the bottom of the screen with 2 options "Take a picture" and "Select existing picture" ?

What happens when you select one of these options? For instance if you select "Take a picture", does it then activate the camera, or not? If it does activate the camera then what happens after you take a picture with the camera?

Last but not least, can you look at the logs ("adb logcat") to see if there is any error message and if so can you paste the text of the log/error into this issue?

I've just tried this on my own device (Samsung Galaxy 3) and it works fine there, but the problem may be a configuration issue or a device issue, I can't tell without a bit more info (see above).

**Comment by leob** [comment]
General advice: do yourself a favor and install Crosswalk! It solves a huge number of problems, apart from improving performance on older devices.

Good chance (no guarantee) that it will fix your problem as well.
