### ISSUE TITLE
logentries

### ISSUE THREAD

**Issue by ofershap** [leob/ionic-quickstarter#38]
can you please explain more about how do you use logentries in your starterkit?

**Comment by leob** [comment]
I believe it's explained in my Wiki but I am not sure about that, I will check it tomorrow.

**Comment by leob** [comment]
No it is not explained in the Wiki, or in the README ... how did you find out that it exists, from the Release Notes maybe? I will write some documentation (Wiki) to explain how to use it.

**Comment by ofershap** [comment]
Youve mentioned it in the Ionic Forums, i searched for an implementation
examole for ionic in google and found your comment on the forum, but no
mention in the kit..  Exploring the kit i just found a minified file of
logentities, so i coudlnt figure out how can i use it properly
Thank you for descriibing the usage and for sharing this beautiful designed
starter kit, great work
בתאריך 16 באפר׳ 2016 9:18 לפנה״צ,‏ "leob" notifications@github.com כתב:

**Comment by leob** [comment]
Thanks for the compliments, good to hear that.

Well I've put a lot of time and effort in the project, including the documentation, but in the end the effort is worth it because I'm using it myself for all my projects and it saves me a lot of time, because a lot of the functionality (signup, authentication, image management) is needed over and over again.

I have plans for adding some more functionality, and I'm also thinking about doing an Ionic 2 version, haven't decided on that but I think if I do that it will probably become very popular.

Anyway I will look at writing some documentation today on the Wiki about Logentries.

**Comment by leob** [comment]
Okay, figured out how to use Logentries because I'd already forgotten it myself.

There are 3 steps to configuring Logentries:

1)  Setting the configuration parameter "tracking" to "true"

2)  Changing `index-template.html` file (https://github.com/leob/ionic-quickstarter/blob/master/src/index-template.html) to activate Logentries initialization and to set your Logentries Token

3)  Modifying the Tracking service (https://github.com/leob/ionic-quickstarter/blob/master/src/js/app/util/services/tracking.service.js) to activate the "Logentries" implementation of the Tracking servce, instead of the "Dummy" implementation of the Tracking service

ad 1) Setting the configuration parameter "tracking" to "true"

The app can run in 2 different "modes": "dev" (development mode) and "prod" (production mode).

Now, normally you would use remote logging (with Logentries) ONLY in "production" mode (when the app runs on a user's device), because you will want to know what is going on on the user's device (especially if there is a problem).

In "development" mode (when you are running the app in a browser with "ionic run") there is no need for remote logging (Logentries) because you can just look at the local console.

This is the reason why "tracking" is set to "false" in the "dev" configuration file (config-dev.json) but to "true" in the "prod"  configuration file (config-prod.json).

So, in https://github.com/leob/ionic-quickstarter/blob/master/src/js/config/config-dev.json it looks like this:

```
...
"tracking": false
...
```

while in https://github.com/leob/ionic-quickstarter/blob/master/src/js/config/config-prod.json is looks like this:

```
...
"tracking": true
...
```

So in "prod" mode the "tracking" parameter is already set (which means that potentially Logentries can be used), while in "dev" mode "tracking" is set to "false" (which means, no Logentries).

If you want "remote" logging (with Logentries) for "dev" mode as well, set the "tracking" parameter to true in `config-dev.json`.

ad 2) Changing `index-template.html`

In the `index-template.html` file, you will see these 4 lines:

```
  <!--<script src="js/lib/logentries/le.min.js"></script>-->
  <!--<script>-->
    <!--LE.init({token: 'PASTE-YOUR-LOGENTRIES-TOKEN-HERE', print: false});-->
  <!--</script>-->
```

You must uncomment these lines, like this:

```
  <script src="js/lib/logentries/le.min.js"></script>
  <script>
    LE.init({token: 'PASTE-YOUR-LOGENTRIES-TOKEN-HERE', print: false});
  </script>
```

Next, you must replace 'PASTE-YOUR-LOGENTRIES-TOKEN-HERE' with your Logentries token, for instance it will look like this (the token value is made up):

LE.init({token: 'xbfbu3j3-1zkp-h54a-8wv7-78a762x823rs', print: false});

ad 3)  Modifying the Tracking service

In the `tracking.service.js` file, you will see these lines:

```
    //if (APP.devMode) {
      return $injector.get('TrackingServiceDummyImpl');
    //} else {
    //  return $injector.get('TrackingServiceLogentriesImpl');
    //}
```

To use Logentries (in production mode), you need to change these lines as follows:

```
    if (APP.devMode) {
      return $injector.get('TrackingServiceDummyImpl');
    } else {
      return $injector.get('TrackingServiceLogentriesImpl');
    }
```

If you want Logentries in "development" mode too, change it as follows:

```
    if (APP.devMode) {
      return $injector.get('TrackingServiceLogentriesImpl');
    } else {
      return $injector.get('TrackingServiceLogentriesImpl');
    }
```

or simply:

```
    return $injector.get('TrackingServiceLogentriesImpl');
```

That's all, with these 3 steps you should have remote logging with Logentries.

I'll add this explanation to the Wiki too (see https://github.com/leob/ionic-quickstarter/wiki/Setting-up-remote-logging-with-Logentries).

**Comment by ofershap** [comment]
Thank you leob for the detailed explenation, i will implement it and if
i'll have any questions i will write you back
בתאריך 16 באפר׳ 2016 22:59,‏ "leob" notifications@github.com כתב:

**Comment by leob** [comment]
You are welcome, I've also added the info to the Wiki. I will close this issue then, if there are questions we can reopen it but you can write back anyway of course.
