### ISSUE TITLE
Side menu will not close.  Tabs are pinned to the top instead of bottom

### ISSUE THREAD

**Issue by jrmcdona** [leob/ionic-quickstarter#42]
Hi, just installed the quick starter and ran the serve -c command.  The Welcome screens opens up and the app loads.

I am unable to close the side menu and the tabs are at the top (maybe that is intentional?).  Here is a screenshot.    I am not seeing any errors in the browser console when click the hamburger icon.

<img width="1149" alt="screen shot 2016-11-17 at 8 11 11 am" src="https://cloud.githubusercontent.com/assets/4327773/20392441/7bb0482c-ac9d-11e6-9165-f67399c5a7df.png">

Thought I would let you know!  

Thanks

**Comment by leob** [comment]
Thanks for opening an issue, nice to see that you've checked out the project!

I can answer both questions right away:

1) Unable to close the side menu:

This is intentional, it is (by default) how Ionic's side menu works when setting the "expose-aside-when" attribute on it. I'm using "expose-aside-when" in the menu (see line 17 of https://github.com/leob/ionic-quickstarter/blob/master/src/js/app/menu/menu.html).

What "expose-aside-when" does is to make the menu "hidden" on smaller screens (e.g. phone) but to always show it on larger screens (tablet). So this behavior is intentional.

See here for the complete story: http://blog.ionic.io/splitview-has-landed/

2) Tabs are always shown at the top:

This is because on line 65 of app.js I'm configuring the tabs to be always at the top, regardless whether the app runs under Android or iOS. See lines 64 and 65 of app.js (https://github.com/leob/ionic-quickstarter/blob/master/src/js/app/app.js):

```
// NOTE: we put the tabs at the top for both Android and iOS
$ionicConfigProvider.tabs.position("top");
```

So this is also intentional (in my opinion the tabs at the bottom are rather ugly but that's purely a matter of taste of course).

Of course you can remove these lines and then you will get the default behavior (tabs at the top for Android, tabs at the bottom for iOS).

**Comment by jrmcdona** [comment]
Ok thanks for the clarification!
